### ISSUE TITLE
ImportError cannot import name mbz

### ISSUE THREAD

**Issue by elearningdave** [ocdude/mbzextract#6]
I am not a Python expert, so hope this makes sense.
Having modified the path at the top of mbextract to the Python interpreter on my system (v2.6 provided by CentOS yum installer), I keep getting the above error.
I tried changing the folder name, and mbz.py is there in the same folder, but it still won't work.
I've tried chmod 777 *.py and that didn't help.

**Comment by ocdude** [comment]
I'm not totally sure this script works with Python 2.6 to be honest. I wrote it originally for Python 2.7 and modified it for Python 3.

You need to keep the whole package together in the `mbzextract` folder and run it from the script provided in the `bin` folder.

If you could paste the exact command you're running and the output, I might be able to take a look, though.

**Comment by elearningdave** [comment]
It's in a folder called mbzextract - here's the return I get:

[root@kaltura mbzextract]# ./mbzextract.py try.zip
Traceback (most recent call last):
  File "./mbzextract.py", line 5, in <module>
    from mbzextract import mbz
  File "/opt/mbzextract/mbzextract.py", line 5, in <module>
    from mbzextract import mbz
ImportError: cannot import name mbz

**Comment by ocdude** [comment]
Go up one folder level, then run:

`python -m mbzextract.mbzextract try.zip`

Again, no guarantees it'll run in Python 2.6, though. It'll be way better if you could install Python 3 and run the script from within the `bin` folder, so `bin/mbzextract try.zip`.

Also, this script is designed to extract files from a .mbz moodle2 and above backup file.

**Comment by elearningdave** [comment]
I installed both Python 2.7 and 3.3 using the following guide:
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4
(so the stock CentOS one was unaffected).

On running the script specifically using 3.3 I got the following error:
[root@kaltura opt]# python3.3 -m mbzextract.mbzextract try.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./mbzextract/mbzextract.py", line 5, in <module>
    from mbzextract import mbz
  File "./mbzextract/mbz.py", line 10, in <module>
    import sqlite3
  File "/usr/local/lib/python3.3/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.3/sqlite3/dbapi2.py", line 26, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

Is there a list of which python plugins I need to install? SQLite seems a bit of an odd one, unless that's how moodle bundles the mbzs up in some way/shape/form?

**Comment by elearningdave** [comment]
(note, python2.7 gives me a similar set of errors to 2.6)

**Comment by ocdude** [comment]
Looks like the directions on digitalocean are missing a step for sqlite3. Check out this stackoverflow thread: http://stackoverflow.com/a/24449632

**Comment by elearningdave** [comment]
Sorry busy day yesterday. I've recompiled Python 3.3 as per the article you linked to (thanks), and after renaming the .zip to .mbz, and putting its absolute path in the command call, it is trying to open it. But I get this output:
[root@kaltura opt]# python3.3 -m mbzextract.mbzextract /opt/mbzextract/try.mbz
Parsing the moodle backup file...
This file is of an unknown type. Exiting.
I can confirm this is a 'good' backup file, as we were sent it by a SCORM provider and it restored into our (v2.9.2) live moodle instance. The backup file said it was made using m2.9.1

**Comment by ocdude** [comment]
I've honestly not tested with SCORM files, only files created from within Moodle itself. I believe Moodle handles SCORM packages through a separate process that's tied to, but not directly using the backup/restore functionality.

SCORM has it's own file structure that my tool doesn't handle.

**Comment by elearningdave** [comment]
I should probably have clarified: the try.mbz file is a full moodle course backup. The resources on the page are mostly SCORMs (but several of them, hence the provider sending us a full moodle course to just restore), but as long as the extractor spits out the ZIP files with the name they were uploaded with, that's fine.
The tutor who asked me to do this, hence finding your script, has mostly words and PDFs etc on his courses

**Comment by ocdude** [comment]
Mind attaching the file here? If not, you can email me at ocdude at bluewavedigital.net and I can take a look. That particular error message really should only happen if the backup file is malformed somehow.
